services:
  codereview:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ".env"

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
