services:
  codereview:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ".env"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  ollama: